version: "0.2"
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - svelte
  - xml
files:
  - "**/.*"
  - "**/*.{css,js,json,jsonc,html,md,scss,svelte,svg,yaml,yml,xml}"
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - data/**/*.json
  - static/assets/**
words:
  - ACTANT
  - Akatsuka
  - atmark
  - Birchill
  - cocosoco
  - cocosocofigure
  - CoMADO
  - Daisuke
  - Dribbble
  - facepile
  - grecaptcha
  - pnpm
  - postcss
  - Ryoko
  - singleline
  - stylelint
  - Sveltia
  - telepresence
  - Ueoka
  - Vite
  - whatiscocosoco
  - zeroinon
